# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'empresas-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for empresas-ios

  pod 'SwiftLint'
  pod 'MaterialComponents/ActivityIndicator'

end
